# Generated by Django 3.2.6 on 2022-06-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
